apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: devops-toolkit
  labels:
    app: devops-toolkit
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: devops-toolkit
          servicePort: 80
    host: devopstoolkitseries.com
